lint:
  multiqc_config: false
  files_exist:
    - tests/default.nf.test
  files_unchanged:
    - .github/CONTRIBUTING.md
    - docs/images/nf-core-seqinspector_logo_dark.png
    - docs/images/nf-core-seqinspector_logo_light.png
    - assets/nf-core-seqinspector_logo_light.png
  nextflow_config:
    - config_defaults:
        - params.fastq_screen_references
nf_core_version: 3.5.1
repository_type: pipeline
template:
  author: Adrien Coulier
  description: Pipeline to QC your sequences
  force: false
  is_nfcore: true
  name: seqinspector
  org: nf-core
  outdir: .
  version: 1.0dev
