%%metro title: nf-core/seqinspector
%%metro style: dark
%%metro logo: docs/images/nf-core-seqinspector_logo_dark.png

%%metro line: fastq_files | FASTQ Files | #ff7f0e
%%metro line: run_folder | Run Folder | #1f77b4

%%metro file: fastq_in | FASTQ
%%metro file: rundir_in | RUNDIR
%%metro file: multiqc | HTML
%%metro legend: bl

graph LR
    subgraph fastq_files [FASTQ Files]
        fastq_in[ ]

        bbmap[BBMap Clumpify]
        bwamem2[BWAmem2]
        fastp[FastP]
        fastqc[FASTQC]
        fastqe[FASTQE]
        fastqscreen[FastQ Screen]
        fq_lint[FQ Lint]
        kraken2[Kraken2]
        krona[Krona]
        picardhs[Picard collecthsmetrics]
        picardmultiple[Picard collectmultiplemetrics]
        riker[Riker multi]
        seqfu[SeqFu Stats]
        seqkit[SeqKit Stats]
        seqtk[Seqtk sample]
        sequali[Sequali]
        toulligqc[ToulligQC]

        fastq_in -->|fastq_files| seqtk

        seqtk -->|fastq_files| bbmap
        seqtk -->|fastq_files| bwamem2
        bwamem2 -->|fastq_files| picardhs
        bwamem2 -->|fastq_files| picardmultiple
        bwamem2 -->|fastq_files| riker
        seqtk -->|fastq_files| fastp
        seqtk -->|fastq_files| fastqc
        seqtk -->|fastq_files| fastqe
        seqtk -->|fastq_files| fastqscreen
        seqtk -->|fastq_files| fq_lint
        seqtk -->|fastq_files| kraken2
        kraken2 -->|fastq_files| krona
        seqtk -->|fastq_files| seqfu
        seqtk -->|fastq_files| seqkit
        seqtk -->|fastq_files| sequali
        seqtk -->|fastq_files| toulligqc
    end

    subgraph run_folder [Run Folder]
        rundir_in[ ]

        checkqc[CheckQC]
        rundirparser[Rundirparser]

        rundir_in -->|run_folder| checkqc
        rundir_in -->|run_folder| rundirparser
    end

    subgraph multiqc [MultiQC]
        multiqc[MultiQC]

        bbmap -->|fastq_files| multiqc
        checkqc -->|run_folder| multiqc
        fastp -->|fastq_files| multiqc
        fastqc -->|fastq_files| multiqc
        fastqe -->|fastq_files| multiqc
        fastqscreen -->|fastq_files| multiqc
        fq_lint -->|fastq_files| multiqc
        krona -->|fastq_files| multiqc
        picardhs -->|fastq_files| multiqc
        picardmultiple -->|fastq_files| multiqc
        riker -->|fastq_files| multiqc
        rundirparser -->|run_folder| multiqc
        seqfu -->|fastq_files| multiqc
        seqkit -->|fastq_files| multiqc
        sequali -->|fastq_files| multiqc
        toulligqc -->|fastq_files| multiqc
    end
